name: "CI: Build and Test"

permissions:
  contents: read

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  dotnet-format:
    name: .Net Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          dotnet-version: '10.0.x' # or the exact SDK from your global.json (e.g. '8.0.100')
          include-prerelease: false
          cache: 'nuget' # optional: caches NuGet packages
      - name: Install dependencies
        run: dotnet restore

      - name: Run dotnet format
        run: dotnet format Serilog.Enrichers.SqlException.sln --exclude ./tests/** --verify-no-changes --verbosity diagnostic

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: dotnet-format
    defaults:
      run:
        shell: pwsh

    env:
      ASPNETCORE_ENVIRONMENT: CI
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: 1

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Install dependencies
        run: |
          dotnet restore `
            --locked-mode

      - name: Build Solution
        run: |
          dotnet build `
            --configuration Release `
            --no-restore     
      - name: Run Tests
        run: |
          dotnet test `
            --configuration Release `
            --no-build `
            --logger trx
